name: wudicainiao-AWVS12-Scan-Agent.yml
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-wudicainiao-AWVS12-Scan-Agent
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync wudicainiao-AWVS12-Scan-Agent
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wudicainiao/AWVS12-Scan-Agent.git"
          source_branch: "master"
          destination_branch: "AWVS12-Scan-Agent"
          github_token: ${{ secrets.PAT }}
      
