name: hajiuhajiu-jdsign1112.yml
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-hajiuhajiu-jdsign1112
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync hajiuhajiu-jdsign1112
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/hajiuhajiu/jdsign1112.git"
          source_branch: "master"
          destination_branch: "jdsign1112"
          github_token: ${{ secrets.PAT }}
      
