name: Algebra-FUN-WeReadScan.yml
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Algebra-FUN-WeReadScan
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Algebra-FUN-WeReadScan
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Algebra-FUN/WeReadScan.git"
          source_branch: "master"
          destination_branch: "WeReadScan"
          github_token: ${{ secrets.PAT }}
      
